// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendMessageAck.proto

package com.creolophus.im.protocol.protobuf;

public final class ProtoSendMessageAck {
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_creolophus_im_protobuf_SendMessageAck_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_creolophus_im_protobuf_SendMessageAck_fieldAccessorTable;
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\024SendMessageAck.proto\022\032com.creolophus.i" +
      "m.protobuf\"#\n\016SendMessageAck\022\021\n\tmessageI" +
      "d\030\001 \001(\003B1\n\032com.creolophus.im.protobufB\023P" +
      "rotoSendMessageAckb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_creolophus_im_protobuf_SendMessageAck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_creolophus_im_protobuf_SendMessageAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_creolophus_im_protobuf_SendMessageAck_descriptor,
        new java.lang.String[] { "MessageId", });
  }
  private ProtoSendMessageAck() {}

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SendMessageAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.creolophus.im.protobuf.SendMessageAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 messageId = 1;</code>
     */
    long getMessageId();
  }

  /**
   * <pre>
   **
   *private Long messageId;
   * </pre>
   *
   * Protobuf type {@code com.creolophus.im.protobuf.SendMessageAck}
   */
  public  static final class SendMessageAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.creolophus.im.protobuf.SendMessageAck)
      SendMessageAckOrBuilder {
    public static final int MESSAGEID_FIELD_NUMBER = 1;
  private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.creolophus.im.protobuf.SendMessageAck)
    private static final ProtoSendMessageAck.SendMessageAck DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<SendMessageAck>
        PARSER = new com.google.protobuf.AbstractParser<SendMessageAck>() {
      @java.lang.Override
      public SendMessageAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendMessageAck(input, extensionRegistry);
      }
    };

    static {
        DEFAULT_INSTANCE = new ProtoSendMessageAck.SendMessageAck();
    }

    private long messageId_;
    private byte memoizedIsInitialized = -1;

    // Use SendMessageAck.newBuilder() to construct.
    private SendMessageAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendMessageAck() {
    }
    private SendMessageAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
        if(!(obj instanceof ProtoSendMessageAck.SendMessageAck)) {
        return super.equals(obj);
      }
        ProtoSendMessageAck.SendMessageAck other = (ProtoSendMessageAck.SendMessageAck) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

      public static ProtoSendMessageAck.SendMessageAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
        return ProtoSendMessageAck.internal_static_com_creolophus_im_protobuf_SendMessageAck_descriptor;
    }

    /**
     * <code>int64 messageId = 1;</code>
     */
    public long getMessageId() {
      return messageId_;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendMessageAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
        return ProtoSendMessageAck.internal_static_com_creolophus_im_protobuf_SendMessageAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(ProtoSendMessageAck.SendMessageAck.class, ProtoSendMessageAck.SendMessageAck.Builder.class);
    }

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0L) {
        output.writeInt64(1, messageId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

      public static Builder newBuilder(ProtoSendMessageAck.SendMessageAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

      public static ProtoSendMessageAck.SendMessageAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

      public static ProtoSendMessageAck.SendMessageAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

      public static ProtoSendMessageAck.SendMessageAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

      public static ProtoSendMessageAck.SendMessageAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

      public static ProtoSendMessageAck.SendMessageAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

      public static ProtoSendMessageAck.SendMessageAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

      public static ProtoSendMessageAck.SendMessageAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

      public static ProtoSendMessageAck.SendMessageAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

      public static ProtoSendMessageAck.SendMessageAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

      public static ProtoSendMessageAck.SendMessageAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

      public static ProtoSendMessageAck.SendMessageAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

      public static ProtoSendMessageAck.SendMessageAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.protobuf.Parser<SendMessageAck> parser() {
      return PARSER;
    }

    /**
     * <pre>
     **
     *private Long messageId;
     * </pre>
     *
     * Protobuf type {@code com.creolophus.im.protobuf.SendMessageAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.creolophus.im.protobuf.SendMessageAck)
            ProtoSendMessageAck.SendMessageAckOrBuilder {
      private long messageId_ ;

        // Construct using ProtoSendMessageAck.SendMessageAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      @java.lang.Override
      public ProtoSendMessageAck.SendMessageAck build() {
          ProtoSendMessageAck.SendMessageAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoSendMessageAck.SendMessageAck buildPartial() {
          ProtoSendMessageAck.SendMessageAck result = new ProtoSendMessageAck.SendMessageAck(this);
        result.messageId_ = messageId_;
        onBuilt();
        return result;
      }

      /**
       * <code>int64 messageId = 1;</code>
       */
      public Builder clearMessageId() {

        messageId_ = 0L;
        onChanged();
        return this;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0L;

        return this;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
          return ProtoSendMessageAck.internal_static_com_creolophus_im_protobuf_SendMessageAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(ProtoSendMessageAck.SendMessageAck.class, ProtoSendMessageAck.SendMessageAck.Builder.class);
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
          return ProtoSendMessageAck.internal_static_com_creolophus_im_protobuf_SendMessageAck_descriptor;
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public ProtoSendMessageAck.SendMessageAck getDefaultInstanceForType() {
          return ProtoSendMessageAck.SendMessageAck.getDefaultInstance();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
          return ProtoSendMessageAck.internal_static_com_creolophus_im_protobuf_SendMessageAck_descriptor;
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

        public Builder mergeFrom(ProtoSendMessageAck.SendMessageAck other) {
            if(other == ProtoSendMessageAck.SendMessageAck.getDefaultInstance()) return this;
        if (other.getMessageId() != 0L) {
          setMessageId(other.getMessageId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }      /**
       * <code>int64 messageId = 1;</code>
       */
      public long getMessageId() {
        return messageId_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
          if(other instanceof ProtoSendMessageAck.SendMessageAck) {
              return mergeFrom((ProtoSendMessageAck.SendMessageAck) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }      /**
       * <code>int64 messageId = 1;</code>
       */
      public Builder setMessageId(long value) {

        messageId_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
          ProtoSendMessageAck.SendMessageAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtoSendMessageAck.SendMessageAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }





      // @@protoc_insertion_point(builder_scope:com.creolophus.im.protobuf.SendMessageAck)
    }

    @java.lang.Override
    public ProtoSendMessageAck.SendMessageAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
