// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMsg.proto

package com.creolophus.im.proto;

public final class LoginUpProto {
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_creolophus_im_proto_LoginUp_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_creolophus_im_proto_LoginUp_fieldAccessorTable;
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\rLoginMsg.proto\022\027com.creolophus.im.proto" +
      "\"\032\n\007LoginUp\022\017\n\007sdkName\030\001 \001(\tB\'\n\027com.creo" +
      "lophus.im.protoB\014LoginUpProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_creolophus_im_proto_LoginUp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_creolophus_im_proto_LoginUp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_creolophus_im_proto_LoginUp_descriptor,
        new java.lang.String[] { "SdkName", });
  }
  private LoginUpProto() {}

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LoginUpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.creolophus.im.proto.LoginMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * int 类型
     * </pre>
     *
     * <code>string sdkName = 1;</code>
     */
    java.lang.String getSdkName();
    /**
     * <pre>
     * int 类型
     * </pre>
     *
     * <code>string sdkName = 1;</code>
     */
    com.google.protobuf.ByteString
        getSdkNameBytes();
  }

  /**
   * Protobuf type {@code com.creolophus.im.proto.LoginMsg}
   */
  public  static final class LoginUp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.creolophus.im.proto.LoginMsg)
      LoginUpOrBuilder {
    public static final int SDKNAME_FIELD_NUMBER = 1;
  private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.creolophus.im.proto.LoginMsg)
    private static final com.creolophus.im.proto.LoginUpProto.LoginUp DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<LoginUp>
        PARSER = new com.google.protobuf.AbstractParser<LoginUp>() {
      @java.lang.Override
      public LoginUp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginUp(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new com.creolophus.im.proto.LoginUpProto.LoginUp();
    }

    private volatile java.lang.Object sdkName_;
    private byte memoizedIsInitialized = -1;

    // Use LoginMsg.newBuilder() to construct.
    private LoginUp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginUp() {
      sdkName_ = "";
    }
    private LoginUp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sdkName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.creolophus.im.proto.LoginUpProto.LoginUp)) {
        return super.equals(obj);
      }
      com.creolophus.im.proto.LoginUpProto.LoginUp other = (com.creolophus.im.proto.LoginUpProto.LoginUp) obj;

      if (!getSdkName()
          .equals(other.getSdkName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }    /**
     * <pre>
     * int 类型
     * </pre>
     *
     * <code>string sdkName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSdkNameBytes() {
      java.lang.Object ref = sdkName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdkName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SDKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSdkName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.creolophus.im.proto.LoginUpProto.internal_static_com_creolophus_im_proto_LoginUp_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginUp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.creolophus.im.proto.LoginUpProto.internal_static_com_creolophus_im_proto_LoginUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.creolophus.im.proto.LoginUpProto.LoginUp.class, com.creolophus.im.proto.LoginUpProto.LoginUp.Builder.class);
    }

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSdkNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sdkName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSdkNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sdkName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * <pre>
     * int 类型
     * </pre>
     *
     * <code>string sdkName = 1;</code>
     */
    public java.lang.String getSdkName() {
      java.lang.Object ref = sdkName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sdkName_ = s;
        return s;
      }
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.creolophus.im.proto.LoginUpProto.LoginUp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.creolophus.im.proto.LoginUpProto.LoginUp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.protobuf.Parser<LoginUp> parser() {
      return PARSER;
    }

    /**
     * Protobuf type {@code com.creolophus.im.proto.LoginMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.creolophus.im.proto.LoginMsg)
        com.creolophus.im.proto.LoginUpProto.LoginUpOrBuilder {
      private java.lang.Object sdkName_ = "";

      // Construct using com.creolophus.im.proto.LoginUpProto.LoginMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      @java.lang.Override
      public com.creolophus.im.proto.LoginUpProto.LoginUp build() {
        com.creolophus.im.proto.LoginUpProto.LoginUp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.creolophus.im.proto.LoginUpProto.LoginUp buildPartial() {
        com.creolophus.im.proto.LoginUpProto.LoginUp result = new com.creolophus.im.proto.LoginUpProto.LoginUp(this);
        result.sdkName_ = sdkName_;
        onBuilt();
        return result;
      }

      /**
       * <pre>
       * int 类型
       * </pre>
       *
       * <code>string sdkName = 1;</code>
       */
      public Builder clearSdkName() {

        sdkName_ = getDefaultInstance().getSdkName();
        onChanged();
        return this;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        sdkName_ = "";

        return this;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.creolophus.im.proto.LoginUpProto.internal_static_com_creolophus_im_proto_LoginUp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.creolophus.im.proto.LoginUpProto.LoginUp.class, com.creolophus.im.proto.LoginUpProto.LoginUp.Builder.class);
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.creolophus.im.proto.LoginUpProto.internal_static_com_creolophus_im_proto_LoginUp_descriptor;
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public com.creolophus.im.proto.LoginUpProto.LoginUp getDefaultInstanceForType() {
        return com.creolophus.im.proto.LoginUpProto.LoginUp.getDefaultInstance();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.creolophus.im.proto.LoginUpProto.internal_static_com_creolophus_im_proto_LoginUp_descriptor;
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      public Builder mergeFrom(com.creolophus.im.proto.LoginUpProto.LoginUp other) {
        if (other == com.creolophus.im.proto.LoginUpProto.LoginUp.getDefaultInstance()) return this;
        if (!other.getSdkName().isEmpty()) {
          sdkName_ = other.sdkName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }      /**
       * <pre>
       * int 类型
       * </pre>
       *
       * <code>string sdkName = 1;</code>
       */
      public java.lang.String getSdkName() {
        java.lang.Object ref = sdkName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sdkName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.creolophus.im.proto.LoginUpProto.LoginUp) {
          return mergeFrom((com.creolophus.im.proto.LoginUpProto.LoginUp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }      /**
       * <pre>
       * int 类型
       * </pre>
       *
       * <code>string sdkName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSdkNameBytes() {
        java.lang.Object ref = sdkName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdkName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.creolophus.im.proto.LoginUpProto.LoginUp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.creolophus.im.proto.LoginUpProto.LoginUp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }      /**
       * <pre>
       * int 类型
       * </pre>
       *
       * <code>string sdkName = 1;</code>
       */
      public Builder setSdkName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        sdkName_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * int 类型
       * </pre>
       *
       * <code>string sdkName = 1;</code>
       */
      public Builder setSdkNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        sdkName_ = value;
        onChanged();
        return this;
      }





      // @@protoc_insertion_point(builder_scope:com.creolophus.im.proto.LoginMsg)
    }



    @java.lang.Override
    public com.creolophus.im.proto.LoginUpProto.LoginUp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
