spring:
  application:
    name: liuyi-im-gateway-sk

  profiles:
    active: demo
  cloud:
    loadbalancer:
      retry:
        enabled: false

beetl-beetlsql:
  dev: true
beetlsql:
  basePackage: com.creolophus.im.dao

k8s:
  liuyi-im-backend: "127.0.0.1:33011"


logging:
  pattern:
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} %p ${spring.application.name} ${X-LiuYi-IP:-} ${server.port} %X{X-B3-TraceId:-} %X{X-B3-SpanId:-} %X{X-LiuYi-EXT:-} %X{X-LiuYi-URI:-} %logger{39}.%X{X-LiuYi-Method:-} %m%n"
    console: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} %p ${spring.application.name} ${X-LiuYi-IP:-} ${server.port} %X{X-B3-TraceId:-} %X{X-B3-SpanId:-} %X{X-LiuYi-EXT:-} %X{X-LiuYi-URI:-} %logger{39}.%X{X-LiuYi-Method:-} %m%n"
  file: "logs/${spring.application.name}.log"
  level:
    root: info
    com:
      creolophus: debug


server:
  port: 33008
  undertow:
    accesslog:
      enabled: true
      pattern: "%h %l %u %t %r %s %b %D"

