// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMsg.proto

package com.creolophus.im.protobuf;

public final class ProtoLoginMsg {
  private ProtoLoginMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.creolophus.im.protobuf.LoginMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string deviceLabel = 1;</code>
     */
    java.lang.String getDeviceLabel();
    /**
     * <code>string deviceLabel = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceLabelBytes();

    /**
     * <code>string sdkName = 2;</code>
     */
    java.lang.String getSdkName();
    /**
     * <code>string sdkName = 2;</code>
     */
    com.google.protobuf.ByteString
        getSdkNameBytes();

    /**
     * <code>string sdkVersion = 3;</code>
     */
    java.lang.String getSdkVersion();
    /**
     * <code>string sdkVersion = 3;</code>
     */
    com.google.protobuf.ByteString
        getSdkVersionBytes();
  }
  /**
   * <pre>
   **
   *private String deviceLabel;
   *private String sdkName;
   *private String sdkVersion;
   * </pre>
   *
   * Protobuf type {@code com.creolophus.im.protobuf.LoginMsg}
   */
  public  static final class LoginMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.creolophus.im.protobuf.LoginMsg)
      LoginMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginMsg.newBuilder() to construct.
    private LoginMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginMsg() {
      deviceLabel_ = "";
      sdkName_ = "";
      sdkVersion_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceLabel_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sdkName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sdkVersion_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.creolophus.im.protobuf.ProtoLoginMsg.internal_static_com_creolophus_im_protobuf_LoginMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.creolophus.im.protobuf.ProtoLoginMsg.internal_static_com_creolophus_im_protobuf_LoginMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg.class, com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg.Builder.class);
    }

    public static final int DEVICELABEL_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceLabel_;
    /**
     * <code>string deviceLabel = 1;</code>
     */
    public java.lang.String getDeviceLabel() {
      java.lang.Object ref = deviceLabel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceLabel_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceLabel = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceLabelBytes() {
      java.lang.Object ref = deviceLabel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceLabel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDKNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object sdkName_;
    /**
     * <code>string sdkName = 2;</code>
     */
    public java.lang.String getSdkName() {
      java.lang.Object ref = sdkName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sdkName_ = s;
        return s;
      }
    }
    /**
     * <code>string sdkName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSdkNameBytes() {
      java.lang.Object ref = sdkName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdkName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDKVERSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object sdkVersion_;
    /**
     * <code>string sdkVersion = 3;</code>
     */
    public java.lang.String getSdkVersion() {
      java.lang.Object ref = sdkVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sdkVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string sdkVersion = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSdkVersionBytes() {
      java.lang.Object ref = sdkVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdkVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceLabel_);
      }
      if (!getSdkNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sdkName_);
      }
      if (!getSdkVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sdkVersion_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceLabel_);
      }
      if (!getSdkNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sdkName_);
      }
      if (!getSdkVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sdkVersion_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg)) {
        return super.equals(obj);
      }
      com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg other = (com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg) obj;

      if (!getDeviceLabel()
          .equals(other.getDeviceLabel())) return false;
      if (!getSdkName()
          .equals(other.getSdkName())) return false;
      if (!getSdkVersion()
          .equals(other.getSdkVersion())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICELABEL_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceLabel().hashCode();
      hash = (37 * hash) + SDKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSdkName().hashCode();
      hash = (37 * hash) + SDKVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getSdkVersion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *private String deviceLabel;
     *private String sdkName;
     *private String sdkVersion;
     * </pre>
     *
     * Protobuf type {@code com.creolophus.im.protobuf.LoginMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.creolophus.im.protobuf.LoginMsg)
        com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.creolophus.im.protobuf.ProtoLoginMsg.internal_static_com_creolophus_im_protobuf_LoginMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.creolophus.im.protobuf.ProtoLoginMsg.internal_static_com_creolophus_im_protobuf_LoginMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg.class, com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg.Builder.class);
      }

      // Construct using com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceLabel_ = "";

        sdkName_ = "";

        sdkVersion_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.creolophus.im.protobuf.ProtoLoginMsg.internal_static_com_creolophus_im_protobuf_LoginMsg_descriptor;
      }

      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg getDefaultInstanceForType() {
        return com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg build() {
        com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg buildPartial() {
        com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg result = new com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg(this);
        result.deviceLabel_ = deviceLabel_;
        result.sdkName_ = sdkName_;
        result.sdkVersion_ = sdkVersion_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg) {
          return mergeFrom((com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg other) {
        if (other == com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg.getDefaultInstance()) return this;
        if (!other.getDeviceLabel().isEmpty()) {
          deviceLabel_ = other.deviceLabel_;
          onChanged();
        }
        if (!other.getSdkName().isEmpty()) {
          sdkName_ = other.sdkName_;
          onChanged();
        }
        if (!other.getSdkVersion().isEmpty()) {
          sdkVersion_ = other.sdkVersion_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceLabel_ = "";
      /**
       * <code>string deviceLabel = 1;</code>
       */
      public java.lang.String getDeviceLabel() {
        java.lang.Object ref = deviceLabel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceLabel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deviceLabel = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceLabelBytes() {
        java.lang.Object ref = deviceLabel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceLabel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceLabel = 1;</code>
       */
      public Builder setDeviceLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceLabel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceLabel = 1;</code>
       */
      public Builder clearDeviceLabel() {
        
        deviceLabel_ = getDefaultInstance().getDeviceLabel();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceLabel = 1;</code>
       */
      public Builder setDeviceLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceLabel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sdkName_ = "";
      /**
       * <code>string sdkName = 2;</code>
       */
      public java.lang.String getSdkName() {
        java.lang.Object ref = sdkName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sdkName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sdkName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSdkNameBytes() {
        java.lang.Object ref = sdkName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdkName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sdkName = 2;</code>
       */
      public Builder setSdkName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sdkName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sdkName = 2;</code>
       */
      public Builder clearSdkName() {
        
        sdkName_ = getDefaultInstance().getSdkName();
        onChanged();
        return this;
      }
      /**
       * <code>string sdkName = 2;</code>
       */
      public Builder setSdkNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sdkName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sdkVersion_ = "";
      /**
       * <code>string sdkVersion = 3;</code>
       */
      public java.lang.String getSdkVersion() {
        java.lang.Object ref = sdkVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sdkVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sdkVersion = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSdkVersionBytes() {
        java.lang.Object ref = sdkVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdkVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sdkVersion = 3;</code>
       */
      public Builder setSdkVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sdkVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sdkVersion = 3;</code>
       */
      public Builder clearSdkVersion() {
        
        sdkVersion_ = getDefaultInstance().getSdkVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string sdkVersion = 3;</code>
       */
      public Builder setSdkVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sdkVersion_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.creolophus.im.protobuf.LoginMsg)
    }

    // @@protoc_insertion_point(class_scope:com.creolophus.im.protobuf.LoginMsg)
    private static final com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg();
    }

    public static com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginMsg>
        PARSER = new com.google.protobuf.AbstractParser<LoginMsg>() {
      @java.lang.Override
      public LoginMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.creolophus.im.protobuf.ProtoLoginMsg.LoginMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_creolophus_im_protobuf_LoginMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_creolophus_im_protobuf_LoginMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016LoginMsg.proto\022\032com.creolophus.im.prot" +
      "obuf\"D\n\010LoginMsg\022\023\n\013deviceLabel\030\001 \001(\t\022\017\n" +
      "\007sdkName\030\002 \001(\t\022\022\n\nsdkVersion\030\003 \001(\tB+\n\032co" +
      "m.creolophus.im.protobufB\rProtoLoginMsgb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_creolophus_im_protobuf_LoginMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_creolophus_im_protobuf_LoginMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_creolophus_im_protobuf_LoginMsg_descriptor,
        new java.lang.String[] { "DeviceLabel", "SdkName", "SdkVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
