// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushMessageAck.proto

package com.creolophus.im.protobuf;

public final class ProtoPushMessageAck {
  private ProtoPushMessageAck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PushMessageAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.creolophus.im.protobuf.PushMessageAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 messageId = 1;</code>
     */
    long getMessageId();

    /**
     * <code>int64 groupId = 2;</code>
     */
    long getGroupId();

    /**
     * <code>int64 receiverId = 3;</code>
     */
    long getReceiverId();

    /**
     * <code>int64 senderId = 4;</code>
     */
    long getSenderId();
  }
  /**
   * <pre>
   **
   *private Long messageId;
   *private Long groupId;
   *private Long receiverId;
   *private Long senderId;
   * </pre>
   *
   * Protobuf type {@code com.creolophus.im.protobuf.PushMessageAck}
   */
  public  static final class PushMessageAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.creolophus.im.protobuf.PushMessageAck)
      PushMessageAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PushMessageAck.newBuilder() to construct.
    private PushMessageAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushMessageAck() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PushMessageAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readInt64();
              break;
            }
            case 16: {

              groupId_ = input.readInt64();
              break;
            }
            case 24: {

              receiverId_ = input.readInt64();
              break;
            }
            case 32: {

              senderId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.creolophus.im.protobuf.ProtoPushMessageAck.internal_static_com_creolophus_im_protobuf_PushMessageAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.creolophus.im.protobuf.ProtoPushMessageAck.internal_static_com_creolophus_im_protobuf_PushMessageAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck.class, com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private long messageId_;
    /**
     * <code>int64 messageId = 1;</code>
     */
    public long getMessageId() {
      return messageId_;
    }

    public static final int GROUPID_FIELD_NUMBER = 2;
    private long groupId_;
    /**
     * <code>int64 groupId = 2;</code>
     */
    public long getGroupId() {
      return groupId_;
    }

    public static final int RECEIVERID_FIELD_NUMBER = 3;
    private long receiverId_;
    /**
     * <code>int64 receiverId = 3;</code>
     */
    public long getReceiverId() {
      return receiverId_;
    }

    public static final int SENDERID_FIELD_NUMBER = 4;
    private long senderId_;
    /**
     * <code>int64 senderId = 4;</code>
     */
    public long getSenderId() {
      return senderId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0L) {
        output.writeInt64(1, messageId_);
      }
      if (groupId_ != 0L) {
        output.writeInt64(2, groupId_);
      }
      if (receiverId_ != 0L) {
        output.writeInt64(3, receiverId_);
      }
      if (senderId_ != 0L) {
        output.writeInt64(4, senderId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageId_);
      }
      if (groupId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, groupId_);
      }
      if (receiverId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, receiverId_);
      }
      if (senderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, senderId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck)) {
        return super.equals(obj);
      }
      com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck other = (com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (getGroupId()
          != other.getGroupId()) return false;
      if (getReceiverId()
          != other.getReceiverId()) return false;
      if (getSenderId()
          != other.getSenderId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageId());
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupId());
      hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiverId());
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSenderId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *private Long messageId;
     *private Long groupId;
     *private Long receiverId;
     *private Long senderId;
     * </pre>
     *
     * Protobuf type {@code com.creolophus.im.protobuf.PushMessageAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.creolophus.im.protobuf.PushMessageAck)
        com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.creolophus.im.protobuf.ProtoPushMessageAck.internal_static_com_creolophus_im_protobuf_PushMessageAck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.creolophus.im.protobuf.ProtoPushMessageAck.internal_static_com_creolophus_im_protobuf_PushMessageAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck.class, com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck.Builder.class);
      }

      // Construct using com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0L;

        groupId_ = 0L;

        receiverId_ = 0L;

        senderId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.creolophus.im.protobuf.ProtoPushMessageAck.internal_static_com_creolophus_im_protobuf_PushMessageAck_descriptor;
      }

      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck getDefaultInstanceForType() {
        return com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck.getDefaultInstance();
      }

      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck build() {
        com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck buildPartial() {
        com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck result = new com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck(this);
        result.messageId_ = messageId_;
        result.groupId_ = groupId_;
        result.receiverId_ = receiverId_;
        result.senderId_ = senderId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck) {
          return mergeFrom((com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck other) {
        if (other == com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck.getDefaultInstance()) return this;
        if (other.getMessageId() != 0L) {
          setMessageId(other.getMessageId());
        }
        if (other.getGroupId() != 0L) {
          setGroupId(other.getGroupId());
        }
        if (other.getReceiverId() != 0L) {
          setReceiverId(other.getReceiverId());
        }
        if (other.getSenderId() != 0L) {
          setSenderId(other.getSenderId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long messageId_ ;
      /**
       * <code>int64 messageId = 1;</code>
       */
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <code>int64 messageId = 1;</code>
       */
      public Builder setMessageId(long value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0L;
        onChanged();
        return this;
      }

      private long groupId_ ;
      /**
       * <code>int64 groupId = 2;</code>
       */
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <code>int64 groupId = 2;</code>
       */
      public Builder setGroupId(long value) {
        
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 groupId = 2;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = 0L;
        onChanged();
        return this;
      }

      private long receiverId_ ;
      /**
       * <code>int64 receiverId = 3;</code>
       */
      public long getReceiverId() {
        return receiverId_;
      }
      /**
       * <code>int64 receiverId = 3;</code>
       */
      public Builder setReceiverId(long value) {
        
        receiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 receiverId = 3;</code>
       */
      public Builder clearReceiverId() {
        
        receiverId_ = 0L;
        onChanged();
        return this;
      }

      private long senderId_ ;
      /**
       * <code>int64 senderId = 4;</code>
       */
      public long getSenderId() {
        return senderId_;
      }
      /**
       * <code>int64 senderId = 4;</code>
       */
      public Builder setSenderId(long value) {
        
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 senderId = 4;</code>
       */
      public Builder clearSenderId() {
        
        senderId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.creolophus.im.protobuf.PushMessageAck)
    }

    // @@protoc_insertion_point(class_scope:com.creolophus.im.protobuf.PushMessageAck)
    private static final com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck();
    }

    public static com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushMessageAck>
        PARSER = new com.google.protobuf.AbstractParser<PushMessageAck>() {
      @java.lang.Override
      public PushMessageAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushMessageAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PushMessageAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PushMessageAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.creolophus.im.protobuf.ProtoPushMessageAck.PushMessageAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_creolophus_im_protobuf_PushMessageAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_creolophus_im_protobuf_PushMessageAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PushMessageAck.proto\022\032com.creolophus.i" +
      "m.protobuf\"Z\n\016PushMessageAck\022\021\n\tmessageI" +
      "d\030\001 \001(\003\022\017\n\007groupId\030\002 \001(\003\022\022\n\nreceiverId\030\003" +
      " \001(\003\022\020\n\010senderId\030\004 \001(\003B1\n\032com.creolophus" +
      ".im.protobufB\023ProtoPushMessageAckb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_creolophus_im_protobuf_PushMessageAck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_creolophus_im_protobuf_PushMessageAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_creolophus_im_protobuf_PushMessageAck_descriptor,
        new java.lang.String[] { "MessageId", "GroupId", "ReceiverId", "SenderId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
