// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package com.creolophus.im.protobuf;

public final class ProtoCommand {
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_creolophus_im_protobuf_Command_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_creolophus_im_protobuf_Command_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_creolophus_im_protobuf_Command_Header_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_creolophus_im_protobuf_Command_Header_fieldAccessorTable;
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto\022\032com.creolophus.im.proto" +
      "buf\032\031google/protobuf/any.proto\"\272\001\n\007Comma" +
      "nd\022\r\n\005token\030\001 \001(\t\022:\n\006header\030\002 \001(\0132*.com." +
      "creolophus.im.protobuf.Command.Header\022\"\n" +
      "\004body\030\003 \001(\0132\024.google.protobuf.Any\032@\n\006Hea" +
      "der\022\013\n\003seq\030\001 \001(\t\022\014\n\004type\030\002 \001(\005\022\014\n\004code\030\003" +
      " \001(\005\022\r\n\005error\030\004 \001(\tB*\n\032com.creolophus.im" +
      ".protobufB\014ProtoCommandb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_com_creolophus_im_protobuf_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_creolophus_im_protobuf_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_creolophus_im_protobuf_Command_descriptor,
        new java.lang.String[] { "Token", "Header", "Body", });
    internal_static_com_creolophus_im_protobuf_Command_Header_descriptor =
      internal_static_com_creolophus_im_protobuf_Command_descriptor.getNestedTypes().get(0);
    internal_static_com_creolophus_im_protobuf_Command_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_creolophus_im_protobuf_Command_Header_descriptor,
        new java.lang.String[] { "Seq", "Type", "Code", "Error", });
    com.google.protobuf.AnyProto.getDescriptor();
  }
  private ProtoCommand() {}

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.creolophus.im.protobuf.Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Any body = 3;</code>
     */
    com.google.protobuf.Any getBody();

    /**
     * <code>.google.protobuf.Any body = 3;</code>
     */
    com.google.protobuf.AnyOrBuilder getBodyOrBuilder();

    /**
     * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
     */
    com.creolophus.im.protobuf.ProtoCommand.Command.Header getHeader();

    /**
     * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
     */
    com.creolophus.im.protobuf.ProtoCommand.Command.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>string token = 1;</code>
     */
    java.lang.String getToken();

    /**
     * <code>string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>.google.protobuf.Any body = 3;</code>
     */
    boolean hasBody();

    /**
     * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
     */
    boolean hasHeader();
  }

  /**
   * Protobuf type {@code com.creolophus.im.protobuf.Command}
   */
  public  static final class Command extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.creolophus.im.protobuf.Command)
      CommandOrBuilder {
    public static final int TOKEN_FIELD_NUMBER = 1;
    public static final int HEADER_FIELD_NUMBER = 2;
    public static final int BODY_FIELD_NUMBER = 3;
  private static final long serialVersionUID = 0L;    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    // @@protoc_insertion_point(class_scope:com.creolophus.im.protobuf.Command)
    private static final com.creolophus.im.protobuf.ProtoCommand.Command DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Command>
        PARSER = new com.google.protobuf.AbstractParser<Command>() {
      @java.lang.Override
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new com.creolophus.im.protobuf.ProtoCommand.Command();
    }    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.creolophus.im.protobuf.ProtoCommand.internal_static_com_creolophus_im_protobuf_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.creolophus.im.protobuf.ProtoCommand.Command.class, com.creolophus.im.protobuf.ProtoCommand.Command.Builder.class);
    }

    private volatile java.lang.Object token_;
    private com.creolophus.im.protobuf.ProtoCommand.Command.Header header_;
    private com.google.protobuf.Any body_;
    private byte memoizedIsInitialized = -1;
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Command() {
      token_ = "";
    }    /**
     * <code>string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 18: {
              com.creolophus.im.protobuf.ProtoCommand.Command.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.creolophus.im.protobuf.ProtoCommand.Command.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.creolophus.im.protobuf.ProtoCommand.internal_static_com_creolophus_im_protobuf_Command_descriptor;
    }    /**
     * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }

    /**
     * <code>string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }    /**
     * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
     */
    public com.creolophus.im.protobuf.ProtoCommand.Command.Header getHeader() {
      return header_ == null ? com.creolophus.im.protobuf.ProtoCommand.Command.Header.getDefaultInstance() : header_;
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }    /**
     * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
     */
    public com.creolophus.im.protobuf.ProtoCommand.Command.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static Builder newBuilder(com.creolophus.im.protobuf.ProtoCommand.Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }    /**
     * <code>.google.protobuf.Any body = 3;</code>
     */
    public boolean hasBody() {
      return body_ != null;
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }    /**
     * <code>.google.protobuf.Any body = 3;</code>
     */
    public com.google.protobuf.Any getBody() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }    /**
     * <code>.google.protobuf.Any body = 3;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      if (header_ != null) {
        output.writeMessage(2, getHeader());
      }
      if (body_ != null) {
        output.writeMessage(3, getBody());
      }
      unknownFields.writeTo(output);
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHeader());
      }
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBody());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.creolophus.im.protobuf.ProtoCommand.Command)) {
        return super.equals(obj);
      }
      com.creolophus.im.protobuf.ProtoCommand.Command other = (com.creolophus.im.protobuf.ProtoCommand.Command) obj;

      if (!getToken()
          .equals(other.getToken())) return false;
      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.creolophus.im.protobuf.ProtoCommand.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }
    public interface HeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.creolophus.im.protobuf.Command.Header)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 code = 3;</code>
       */
      int getCode();

      /**
       * <code>string error = 4;</code>
       */
      java.lang.String getError();

      /**
       * <code>string error = 4;</code>
       */
      com.google.protobuf.ByteString
          getErrorBytes();

      /**
       * <code>string seq = 1;</code>
       */
      java.lang.String getSeq();

      /**
       * <code>string seq = 1;</code>
       */
      com.google.protobuf.ByteString
          getSeqBytes();

      /**
       * <code>int32 type = 2;</code>
       */
      int getType();
    }

    /**
     * Protobuf type {@code com.creolophus.im.protobuf.Command.Header}
     */
    public  static final class Header extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.creolophus.im.protobuf.Command.Header)
        HeaderOrBuilder {
      public static final int SEQ_FIELD_NUMBER = 1;
      public static final int TYPE_FIELD_NUMBER = 2;
      public static final int CODE_FIELD_NUMBER = 3;
      public static final int ERROR_FIELD_NUMBER = 4;      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
    private static final long serialVersionUID = 0L;
      // @@protoc_insertion_point(class_scope:com.creolophus.im.protobuf.Command.Header)
      private static final com.creolophus.im.protobuf.ProtoCommand.Command.Header DEFAULT_INSTANCE;
      private static final com.google.protobuf.Parser<Header>
          PARSER = new com.google.protobuf.AbstractParser<Header>() {
        @java.lang.Override
        public Header parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Header(input, extensionRegistry);
        }
      };      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.creolophus.im.protobuf.ProtoCommand.internal_static_com_creolophus_im_protobuf_Command_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.creolophus.im.protobuf.ProtoCommand.Command.Header.class, com.creolophus.im.protobuf.ProtoCommand.Command.Header.Builder.class);
      }

      static {
        DEFAULT_INSTANCE = new com.creolophus.im.protobuf.ProtoCommand.Command.Header();
      }

      private volatile java.lang.Object seq_;
      private int type_;
      private int code_;      /**
       * <code>string seq = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSeqBytes() {
        java.lang.Object ref = seq_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          seq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      private volatile java.lang.Object error_;
      private byte memoizedIsInitialized = -1;
      // Use Header.newBuilder() to construct.
      private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }      /**
       * <code>int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }

      private Header() {
        seq_ = "";
        error_ = "";
      }
      private Header(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                seq_ = s;
                break;
              }
              case 16: {

                type_ = input.readInt32();
                break;
              }
              case 24: {

                code_ = input.readInt32();
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                error_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.creolophus.im.protobuf.ProtoCommand.Command.Header)) {
          return super.equals(obj);
        }
        com.creolophus.im.protobuf.ProtoCommand.Command.Header other = (com.creolophus.im.protobuf.ProtoCommand.Command.Header) obj;

        if (!getSeq()
            .equals(other.getSeq())) return false;
        if (getType()
            != other.getType()) return false;
        if (getCode()
            != other.getCode()) return false;
        if (!getError()
            .equals(other.getError())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }      /**
       * <code>int32 code = 3;</code>
       */
      public int getCode() {
        return code_;
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.creolophus.im.protobuf.ProtoCommand.internal_static_com_creolophus_im_protobuf_Command_Header_descriptor;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Header> getParserForType() {
        return PARSER;
      }      /**
       * <code>string error = 4;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        }
      }

      /**
       * <code>string seq = 1;</code>
       */
      public java.lang.String getSeq() {
        java.lang.Object ref = seq_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          seq_ = s;
          return s;
        }
      }      /**
       * <code>string error = 4;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }

      public static Builder newBuilder(com.creolophus.im.protobuf.ProtoCommand.Command.Header prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getSeqBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, seq_);
        }
        if (type_ != 0) {
          output.writeInt32(2, type_);
        }
        if (code_ != 0) {
          output.writeInt32(3, code_);
        }
        if (!getErrorBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, error_);
        }
        unknownFields.writeTo(output);
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getSeqBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, seq_);
        }
        if (type_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, type_);
        }
        if (code_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, code_);
        }
        if (!getErrorBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, error_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SEQ_FIELD_NUMBER;
        hash = (53 * hash) + getSeq().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }

      public static com.creolophus.im.protobuf.ProtoCommand.Command.Header parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static com.google.protobuf.Parser<Header> parser() {
        return PARSER;
      }

      /**
       * Protobuf type {@code com.creolophus.im.protobuf.Command.Header}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.creolophus.im.protobuf.Command.Header)
          com.creolophus.im.protobuf.ProtoCommand.Command.HeaderOrBuilder {
        private java.lang.Object seq_ = "";
        private int type_ ;        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.creolophus.im.protobuf.ProtoCommand.internal_static_com_creolophus_im_protobuf_Command_Header_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.creolophus.im.protobuf.ProtoCommand.Command.Header.class, com.creolophus.im.protobuf.ProtoCommand.Command.Header.Builder.class);
        }
        private int code_ ;
        private java.lang.Object error_ = "";
        // Construct using com.creolophus.im.protobuf.ProtoCommand.Command.Header.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }        @java.lang.Override
        public Builder clear() {
          super.clear();
          seq_ = "";

          type_ = 0;

          code_ = 0;

          error_ = "";

          return this;
        }

        @java.lang.Override
        public com.creolophus.im.protobuf.ProtoCommand.Command.Header build() {
          com.creolophus.im.protobuf.ProtoCommand.Command.Header result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.creolophus.im.protobuf.ProtoCommand.internal_static_com_creolophus_im_protobuf_Command_Header_descriptor;
        }

        /**
         * <code>int32 code = 3;</code>
         */
        public Builder clearCode() {

          code_ = 0;
          onChanged();
          return this;
        }

        /**
         * <code>string error = 4;</code>
         */
        public Builder clearError() {

          error_ = getDefaultInstance().getError();
          onChanged();
          return this;
        }

        /**
         * <code>string seq = 1;</code>
         */
        public Builder clearSeq() {

          seq_ = getDefaultInstance().getSeq();
          onChanged();
          return this;
        }        @java.lang.Override
        public com.creolophus.im.protobuf.ProtoCommand.Command.Header buildPartial() {
          com.creolophus.im.protobuf.ProtoCommand.Command.Header result = new com.creolophus.im.protobuf.ProtoCommand.Command.Header(this);
          result.seq_ = seq_;
          result.type_ = type_;
          result.code_ = code_;
          result.error_ = error_;
          onBuilt();
          return result;
        }

        /**
         * <code>int32 type = 2;</code>
         */
        public Builder clearType() {

          type_ = 0;
          onChanged();
          return this;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }

        @java.lang.Override
        public com.creolophus.im.protobuf.ProtoCommand.Command.Header getDefaultInstanceForType() {
          return com.creolophus.im.protobuf.ProtoCommand.Command.Header.getDefaultInstance();
        }        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }

        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.creolophus.im.protobuf.ProtoCommand.internal_static_com_creolophus_im_protobuf_Command_Header_descriptor;
        }        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }

        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.creolophus.im.protobuf.ProtoCommand.Command.Header) {
            return mergeFrom((com.creolophus.im.protobuf.ProtoCommand.Command.Header)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.creolophus.im.protobuf.ProtoCommand.Command.Header other) {
          if (other == com.creolophus.im.protobuf.ProtoCommand.Command.Header.getDefaultInstance()) return this;
          if (!other.getSeq().isEmpty()) {
            seq_ = other.seq_;
            onChanged();
          }
          if (other.getType() != 0) {
            setType(other.getType());
          }
          if (other.getCode() != 0) {
            setCode(other.getCode());
          }
          if (!other.getError().isEmpty()) {
            error_ = other.error_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }



        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.creolophus.im.protobuf.ProtoCommand.Command.Header parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.creolophus.im.protobuf.ProtoCommand.Command.Header) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }


        /**
         * <code>string seq = 1;</code>
         */
        public java.lang.String getSeq() {
          java.lang.Object ref = seq_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            seq_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string seq = 1;</code>
         */
        public com.google.protobuf.ByteString
            getSeqBytes() {
          java.lang.Object ref = seq_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            seq_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string seq = 1;</code>
         */
        public Builder setSeq(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          seq_ = value;
          onChanged();
          return this;
        }

        /**
         * <code>string seq = 1;</code>
         */
        public Builder setSeqBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          seq_ = value;
          onChanged();
          return this;
        }


        /**
         * <code>int32 type = 2;</code>
         */
        public int getType() {
          return type_;
        }
        /**
         * <code>int32 type = 2;</code>
         */
        public Builder setType(int value) {

          type_ = value;
          onChanged();
          return this;
        }



        /**
         * <code>int32 code = 3;</code>
         */
        public int getCode() {
          return code_;
        }
        /**
         * <code>int32 code = 3;</code>
         */
        public Builder setCode(int value) {

          code_ = value;
          onChanged();
          return this;
        }



        /**
         * <code>string error = 4;</code>
         */
        public java.lang.String getError() {
          java.lang.Object ref = error_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            error_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string error = 4;</code>
         */
        public com.google.protobuf.ByteString
            getErrorBytes() {
          java.lang.Object ref = error_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            error_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string error = 4;</code>
         */
        public Builder setError(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          error_ = value;
          onChanged();
          return this;
        }

        /**
         * <code>string error = 4;</code>
         */
        public Builder setErrorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          error_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.creolophus.im.protobuf.Command.Header)
      }





      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }













      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoCommand.Command.Header getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    /**
     * Protobuf type {@code com.creolophus.im.protobuf.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.creolophus.im.protobuf.Command)
        com.creolophus.im.protobuf.ProtoCommand.CommandOrBuilder {
      private java.lang.Object token_ = "";
      private com.creolophus.im.protobuf.ProtoCommand.Command.Header header_;      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.creolophus.im.protobuf.ProtoCommand.internal_static_com_creolophus_im_protobuf_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.creolophus.im.protobuf.ProtoCommand.Command.class, com.creolophus.im.protobuf.ProtoCommand.Command.Builder.class);
      }
      private com.google.protobuf.SingleFieldBuilderV3<
          com.creolophus.im.protobuf.ProtoCommand.Command.Header, com.creolophus.im.protobuf.ProtoCommand.Command.Header.Builder, com.creolophus.im.protobuf.ProtoCommand.Command.HeaderOrBuilder> headerBuilder_;
      private com.google.protobuf.Any body_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
      // Construct using com.creolophus.im.protobuf.ProtoCommand.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }      @java.lang.Override
      public Builder clear() {
        super.clear();
        token_ = "";

        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        return this;
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.creolophus.im.protobuf.ProtoCommand.internal_static_com_creolophus_im_protobuf_Command_descriptor;
      }

      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoCommand.Command getDefaultInstanceForType() {
        return com.creolophus.im.protobuf.ProtoCommand.Command.getDefaultInstance();
      }

      /**
       * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoCommand.Command build() {
        com.creolophus.im.protobuf.ProtoCommand.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      /**
       * <code>string token = 1;</code>
       */
      public Builder clearToken() {

        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoCommand.Command buildPartial() {
        com.creolophus.im.protobuf.ProtoCommand.Command result = new com.creolophus.im.protobuf.ProtoCommand.Command(this);
        result.token_ = token_;
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public com.google.protobuf.Any.Builder getBodyBuilder() {

        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.creolophus.im.protobuf.ProtoCommand.internal_static_com_creolophus_im_protobuf_Command_descriptor;
      }      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      /**
       * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
       */
      public com.creolophus.im.protobuf.ProtoCommand.Command.Header.Builder getHeaderBuilder() {

        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      /**
       * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.creolophus.im.protobuf.ProtoCommand.Command.Header, com.creolophus.im.protobuf.ProtoCommand.Command.Header.Builder, com.creolophus.im.protobuf.ProtoCommand.Command.HeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.creolophus.im.protobuf.ProtoCommand.Command.Header, com.creolophus.im.protobuf.ProtoCommand.Command.Header.Builder, com.creolophus.im.protobuf.ProtoCommand.Command.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public Builder mergeBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              com.google.protobuf.Any.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.creolophus.im.protobuf.ProtoCommand.Command) {
          return mergeFrom((com.creolophus.im.protobuf.ProtoCommand.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.creolophus.im.protobuf.ProtoCommand.Command other) {
        if (other == com.creolophus.im.protobuf.ProtoCommand.Command.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      /**
       * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
       */
      public Builder mergeHeader(com.creolophus.im.protobuf.ProtoCommand.Command.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.creolophus.im.protobuf.ProtoCommand.Command.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public Builder setBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.creolophus.im.protobuf.ProtoCommand.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.creolophus.im.protobuf.ProtoCommand.Command) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
       */
      public Builder setHeader(com.creolophus.im.protobuf.ProtoCommand.Command.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        token_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        token_ = value;
        onChanged();
        return this;
      }



      /**
       * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
       */
      public com.creolophus.im.protobuf.ProtoCommand.Command.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.creolophus.im.protobuf.ProtoCommand.Command.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }

      /**
       * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
       */
      public Builder setHeader(
          com.creolophus.im.protobuf.ProtoCommand.Command.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }



      /**
       * <code>.com.creolophus.im.protobuf.Command.Header header = 2;</code>
       */
      public com.creolophus.im.protobuf.ProtoCommand.Command.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.creolophus.im.protobuf.ProtoCommand.Command.Header.getDefaultInstance() : header_;
        }
      }




      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public com.google.protobuf.Any getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }

      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public Builder setBody(
          com.google.protobuf.Any.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }



      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : body_;
        }
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.creolophus.im.protobuf.Command)
    }







    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }


    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }











    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.creolophus.im.protobuf.ProtoCommand.Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
