// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendMessageMsg.proto

package com.creolophus.im.protobuf;

public final class ProtoSendMessageMsg {
  private ProtoSendMessageMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SendMessageMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.creolophus.im.protobuf.SendMessageMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 messageType = 1;</code>
     */
    int getMessageType();

    /**
     * <code>int64 targetId = 2;</code>
     */
    long getTargetId();

    /**
     * <code>string messageBody = 3;</code>
     */
    java.lang.String getMessageBody();
    /**
     * <code>string messageBody = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBodyBytes();
  }
  /**
   * <pre>
   **
   *private Integer messageType;
   *private Long targetId;
   *private String messageBody;
   * </pre>
   *
   * Protobuf type {@code com.creolophus.im.protobuf.SendMessageMsg}
   */
  public  static final class SendMessageMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.creolophus.im.protobuf.SendMessageMsg)
      SendMessageMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendMessageMsg.newBuilder() to construct.
    private SendMessageMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendMessageMsg() {
      messageBody_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendMessageMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageType_ = input.readInt32();
              break;
            }
            case 16: {

              targetId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              messageBody_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.creolophus.im.protobuf.ProtoSendMessageMsg.internal_static_com_creolophus_im_protobuf_SendMessageMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.creolophus.im.protobuf.ProtoSendMessageMsg.internal_static_com_creolophus_im_protobuf_SendMessageMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg.class, com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg.Builder.class);
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <code>int32 messageType = 1;</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    public static final int TARGETID_FIELD_NUMBER = 2;
    private long targetId_;
    /**
     * <code>int64 targetId = 2;</code>
     */
    public long getTargetId() {
      return targetId_;
    }

    public static final int MESSAGEBODY_FIELD_NUMBER = 3;
    private volatile java.lang.Object messageBody_;
    /**
     * <code>string messageBody = 3;</code>
     */
    public java.lang.String getMessageBody() {
      java.lang.Object ref = messageBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageBody_ = s;
        return s;
      }
    }
    /**
     * <code>string messageBody = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBodyBytes() {
      java.lang.Object ref = messageBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageType_ != 0) {
        output.writeInt32(1, messageType_);
      }
      if (targetId_ != 0L) {
        output.writeInt64(2, targetId_);
      }
      if (!getMessageBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageType_);
      }
      if (targetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, targetId_);
      }
      if (!getMessageBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg)) {
        return super.equals(obj);
      }
      com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg other = (com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg) obj;

      if (getMessageType()
          != other.getMessageType()) return false;
      if (getTargetId()
          != other.getTargetId()) return false;
      if (!getMessageBody()
          .equals(other.getMessageBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      hash = (37 * hash) + TARGETID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTargetId());
      hash = (37 * hash) + MESSAGEBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMessageBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *private Integer messageType;
     *private Long targetId;
     *private String messageBody;
     * </pre>
     *
     * Protobuf type {@code com.creolophus.im.protobuf.SendMessageMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.creolophus.im.protobuf.SendMessageMsg)
        com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.creolophus.im.protobuf.ProtoSendMessageMsg.internal_static_com_creolophus_im_protobuf_SendMessageMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.creolophus.im.protobuf.ProtoSendMessageMsg.internal_static_com_creolophus_im_protobuf_SendMessageMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg.class, com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg.Builder.class);
      }

      // Construct using com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageType_ = 0;

        targetId_ = 0L;

        messageBody_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.creolophus.im.protobuf.ProtoSendMessageMsg.internal_static_com_creolophus_im_protobuf_SendMessageMsg_descriptor;
      }

      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg getDefaultInstanceForType() {
        return com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg build() {
        com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg buildPartial() {
        com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg result = new com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg(this);
        result.messageType_ = messageType_;
        result.targetId_ = targetId_;
        result.messageBody_ = messageBody_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg) {
          return mergeFrom((com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg other) {
        if (other == com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg.getDefaultInstance()) return this;
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        if (other.getTargetId() != 0L) {
          setTargetId(other.getTargetId());
        }
        if (!other.getMessageBody().isEmpty()) {
          messageBody_ = other.messageBody_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageType_ ;
      /**
       * <code>int32 messageType = 1;</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <code>int32 messageType = 1;</code>
       */
      public Builder setMessageType(int value) {
        
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageType = 1;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private long targetId_ ;
      /**
       * <code>int64 targetId = 2;</code>
       */
      public long getTargetId() {
        return targetId_;
      }
      /**
       * <code>int64 targetId = 2;</code>
       */
      public Builder setTargetId(long value) {
        
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 targetId = 2;</code>
       */
      public Builder clearTargetId() {
        
        targetId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object messageBody_ = "";
      /**
       * <code>string messageBody = 3;</code>
       */
      public java.lang.String getMessageBody() {
        java.lang.Object ref = messageBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageBody = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBodyBytes() {
        java.lang.Object ref = messageBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageBody = 3;</code>
       */
      public Builder setMessageBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageBody = 3;</code>
       */
      public Builder clearMessageBody() {
        
        messageBody_ = getDefaultInstance().getMessageBody();
        onChanged();
        return this;
      }
      /**
       * <code>string messageBody = 3;</code>
       */
      public Builder setMessageBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageBody_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.creolophus.im.protobuf.SendMessageMsg)
    }

    // @@protoc_insertion_point(class_scope:com.creolophus.im.protobuf.SendMessageMsg)
    private static final com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg();
    }

    public static com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendMessageMsg>
        PARSER = new com.google.protobuf.AbstractParser<SendMessageMsg>() {
      @java.lang.Override
      public SendMessageMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendMessageMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendMessageMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendMessageMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.creolophus.im.protobuf.ProtoSendMessageMsg.SendMessageMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_creolophus_im_protobuf_SendMessageMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_creolophus_im_protobuf_SendMessageMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SendMessageMsg.proto\022\032com.creolophus.i" +
      "m.protobuf\"L\n\016SendMessageMsg\022\023\n\013messageT" +
      "ype\030\001 \001(\005\022\020\n\010targetId\030\002 \001(\003\022\023\n\013messageBo" +
      "dy\030\003 \001(\tB1\n\032com.creolophus.im.protobufB\023" +
      "ProtoSendMessageMsgb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_creolophus_im_protobuf_SendMessageMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_creolophus_im_protobuf_SendMessageMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_creolophus_im_protobuf_SendMessageMsg_descriptor,
        new java.lang.String[] { "MessageType", "TargetId", "MessageBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
